### ISSUE TITLE
when

### ISSUE THREAD

**Issue by Hi-doki** [TheSilentD3ath/UtopiaMC-Modpack#1]
![image](https://github.com/user-attachments/assets/0639d7eb-c3d9-42e2-abca-a2d3127d8edd)
I've been waiting months for femboy release :<<< whennnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn

**Comment by TheSilentD3ath** [comment]
Read the description of my modpack:3
I will get my ass up and work on finalizing a server pack and new update in the Christmas holidays so I can release it in the new year. 
Also I wanted to make a small patch for the Christmas holidays if I find time for that.

The thing is I'm a full time computer science student which is why I don't have a lot of time to work on it 😵‍💫

But it would be very helpful if you could tell me directly what you would want to be added in the modpack.

**Comment by TheSilentD3ath** [comment]
The Christmas update was just released:3

**Comment by Hi-doki** [comment]
YAYAYAYAYAYYY >:333
